zinit ice wait"0" lucid ver"$DOTS_ZSH_ABBR_HASH"
zinit load olets/zsh-abbr

ABBR_SET_EXPANSION_CURSOR=1
ABBR_SET_LINE_CURSOR=1
ABBR_GET_AVAILABLE_ABBREVIATION=1
ABBR_LOG_AVAILABLE_ABBREVIATION_AFTER=1
