alias gs='git status'
alias gl='git log --oneline --graph --decorate'
alias gla='git log --oneline --graph --decorate --all'
alias gb='git branch'
alias gd='git diff'
alias gdc='git diff --cached'

alias ga='git add -p'
alias gadd='git add'
alias gc='git commit'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gp='git push'
alias gpl='git pull'

alias gri='git rebase -i'
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias gcp='git cherry-pick'
alias gst='git stash'
alias gsta='git stash apply'
alias gstp='git stash pop'
alias gundo='git reset --soft HEAD~1'
alias greset='git reset --hard HEAD'

alias gbm='git branch -m'
alias gbd='git branch -d'
alias gba='git branch -a'

alias gf='git fetch'
alias gfa='git fetch --all'
alias gpo='git push origin'